/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package calculadora_view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author Juliano Schaurich
 */
public class CalculadoraTela extends javax.swing.JFrame {

    /** Creates new form CalculadoraTela */
    public CalculadoraTela() {
        super("Calculadora V1");
        initComponents();
        buttonSomar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                somar(textField.getText(), textField2.getText());
            }
        });
        buttonSubtrair.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                subtrair(textField.getText(), textField2.getText());
            }
        });
        buttonMultiplicar.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                multiplicar(textField.getText(), textField2.getText());
            }
        });
        buttonDividir.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                dividir(textField.getText(), textField2.getText());
            }
        });
        buttonFatorial.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                fatorial(textField.getText());
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textField = new javax.swing.JTextField();
        textField2 = new javax.swing.JTextField();
        buttonSomar = new javax.swing.JButton();
        labelResultado = new javax.swing.JLabel();
        buttonSubtrair = new javax.swing.JButton();
        buttonMultiplicar = new javax.swing.JButton();
        buttonDividir = new javax.swing.JButton();
        buttonFatorial = new javax.swing.JButton();
        labelLegenda = new javax.swing.JLabel();
        labelLegenda2 = new javax.swing.JLabel();
        labelSegundoNumero = new javax.swing.JLabel();
        labelPrimeiroNumero = new javax.swing.JLabel();
        labelLegenda3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        buttonSomar.setBackground(new java.awt.Color(0, 0, 0));
        buttonSomar.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        buttonSomar.setForeground(new java.awt.Color(255, 255, 255));
        buttonSomar.setText("SOMAR");
        buttonSomar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSomarActionPerformed(evt);
            }
        });

        labelResultado.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N

        buttonSubtrair.setBackground(new java.awt.Color(0, 0, 0));
        buttonSubtrair.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        buttonSubtrair.setForeground(new java.awt.Color(255, 255, 255));
        buttonSubtrair.setText("SUBTRAIR");

        buttonMultiplicar.setBackground(new java.awt.Color(0, 0, 0));
        buttonMultiplicar.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        buttonMultiplicar.setForeground(new java.awt.Color(255, 255, 255));
        buttonMultiplicar.setText("MULTIPLICAR");
        buttonMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMultiplicarActionPerformed(evt);
            }
        });

        buttonDividir.setBackground(new java.awt.Color(0, 0, 0));
        buttonDividir.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        buttonDividir.setForeground(new java.awt.Color(255, 255, 255));
        buttonDividir.setText("DIVIDIR");

        buttonFatorial.setBackground(new java.awt.Color(0, 0, 0));
        buttonFatorial.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        buttonFatorial.setForeground(new java.awt.Color(255, 255, 255));
        buttonFatorial.setText("FATORIAL");
        buttonFatorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFatorialActionPerformed(evt);
            }
        });

        labelLegenda.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        labelLegenda.setText("*Preencher os dois espaços e depois selecionar a operação desejada.");

        labelLegenda2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        labelLegenda2.setText("*Para FATORIAL somente o valor do PRIMEIRO Nº será considerado.");

        labelSegundoNumero.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        labelSegundoNumero.setText("SEGUNDO Nº");

        labelPrimeiroNumero.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        labelPrimeiroNumero.setText("PRIMEIRO Nº");

        labelLegenda3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        labelLegenda3.setText("RESULTADO:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelLegenda3)
                        .addGap(18, 18, 18)
                        .addComponent(labelResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelLegenda)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buttonSubtrair, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonFatorial, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonSomar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(labelPrimeiroNumero)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(buttonDividir, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(textField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(buttonMultiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textField2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelSegundoNumero)))
                    .addComponent(labelLegenda2))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(buttonSomar)
                .addGap(18, 18, 18)
                .addComponent(buttonSubtrair)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonMultiplicar)
                    .addComponent(textField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textField2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buttonDividir)
                        .addComponent(labelSegundoNumero))
                    .addComponent(labelPrimeiroNumero))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(buttonFatorial)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(labelLegenda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelLegenda2)
                        .addGap(63, 63, 63)
                        .addComponent(labelResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(labelLegenda3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void limparTextFields(){
        textField.setText(" ");
        textField2.setText(" ");
    }
    public void somar(String numero1, String numero2) {
        try {
            double d1 = Double.parseDouble(numero1);
            double d2 = Double.parseDouble(numero2);
            
            labelResultado.setText(Double.toString(d1 + d2));
            limparTextFields();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Digite um número válido");
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null, "Digite um número válido");
        }
    }
    public void subtrair(String numero1, String numero2) {
        try {
            double d1 = Double.parseDouble(numero1);
            double d2 = Double.parseDouble(numero2);
            
            labelResultado.setText(Double.toString(d1 - d2));
            limparTextFields();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Digite um número válido");
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null, "Digite um número válido");
        }
    }
    public void multiplicar(String numero1, String numero2) {
        try {
            double d1 = Double.parseDouble(numero1);
            double d2 = Double.parseDouble(numero2);
            
            labelResultado.setText(Double.toString(d1 * d2));
            limparTextFields();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Digite um número válido");
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null, "Digite um número válido");
        }
    }
    public void dividir(String numero1, String numero2) {
        try {
            double d1 = Double.parseDouble(numero1);
            double d2 = Double.parseDouble(numero2);
            
            labelResultado.setText(Double.toString(d1 / d2));
            limparTextFields();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Digite um número válido");
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null, "Digite um número válido");
        }
    }
    public void fatorial(String numero) {
        try {
            double d1 = Double.parseDouble(numero);
            for (int i = 1; i < Double.parseDouble(numero); i++) {
                d1 = d1*i;
              }
            labelResultado.setText(Double.toString(d1));
            limparTextFields();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Digite um número válido");
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null, "Digite um número válido");
        }    
    }
    private void buttonSomarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSomarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSomarActionPerformed

    private void buttonFatorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFatorialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonFatorialActionPerformed

    private void buttonMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMultiplicarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonMultiplicarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDividir;
    private javax.swing.JButton buttonFatorial;
    private javax.swing.JButton buttonMultiplicar;
    private javax.swing.JButton buttonSomar;
    private javax.swing.JButton buttonSubtrair;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelLegenda;
    private javax.swing.JLabel labelLegenda2;
    private javax.swing.JLabel labelLegenda3;
    private javax.swing.JLabel labelPrimeiroNumero;
    private javax.swing.JLabel labelResultado;
    private javax.swing.JLabel labelSegundoNumero;
    private javax.swing.JTextField textField;
    private javax.swing.JTextField textField2;
    // End of variables declaration//GEN-END:variables

}
